services:
  promethee-app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: promethee_container
    ports:
      - "8080:8080"
    restart: always
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
  
  database_postgres:    
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: database_container
    environment:
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_USER: ${postgres_user}
      POSTGRES_DB: ${db_name}
    volumes:
      - ${HOME}/postgres-data/:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql    
